### ISSUE TITLE
search results PageOutQuery image base64

### ISSUE THREAD

**Issue by HalemoGPA** [tjmlabs/ColiVara#91]
The results.results is a list of PageOutQuery including img_base64.

Similar to list_documents when we changed it from returning img_base64 to url. Returning the url here also might be a good approach.

**Comment by HalemoGPA** [comment]
Also QueryOut has the same problem

**Comment by Jonathan-Adly** [comment]
I am closing this - we wouldn't fix this because the primary use case for this is to pass them to LLMs to answer questions. AWS pre-signed URLs don't play nice with LLMs api (see: https://community.openai.com/t/invalid-image-error-in-gpt-4o-when-using-s3-presigned-url/794549/6)

Images need to be base64 for user ease. Files, don't need to be
